### PR TITLE
Limit non-canonical inconsistency detection to selected opcodes

### LINKED ISSUE #1031: Account for other general protection fault possibilities when detecting inconsistencies in non-canonical crashes
As mentioned in the discussion following https://github.com/rust-minidump/rust-minidump/issues/732#issuecomment-2370428678, unaligned accesses (and other cases of general protection fault) causes the OS to report the same crash addresses and exceptions as a crash caused by the use of non-canonical addresses. Currently we can't deduce whether the instruction is performing an unaligned accesses, so we should limit the inconsistency detection to instructions whose only possible cause of GPF is using non-canonical addresses.

### PR DESCRIPTION
**Pull request by BrianShTsoi**
Resolves  #1031

Also renamed a few functions/variables to better distinguish between general protection fault and non-canonical crash.

### CODE REVIEW

File: minidump-processor/src/op_analysis.rs [hunk 1]
```diff
@@ -338,6 +348,18 @@ mod amd64 {
...
+
+        /// Since we only detect inconsistencies in non-canonical crashes if we can derive all its access,
+        /// this function always return false for opcodes that are not `AccessDerivableOpcode`
+        fn is_only_gpf_when_non_canonical(instruction: Instruction) -> bool {
+            let Some(opcode) = AccessDerivableOpcode::from_opcode(instruction.opcode()) else {
+                return false;
+            };
+            !matches!(
+                opcode,
+                AccessDerivableOpcode::MOVAPS | AccessDerivableOpcode::UCOMISS
```
Comment (gabrielesvelto) [inline minidump-processor/src/op_analysis.rs:360]: `MOVAPS` description in Intel manual states that it raises a general-protection fault when the address is unaligned, but `UCOMISS` instruction doesn't mention any alignment requirements, nor that it raise #GP for other conditions. Do we have crashes where the crashing instruction is `UCOMISS` and we get a #GP without a non-canonical address? IIRC we had some odd crashes involving `UCOMISS` but they were cause by a bug in QEMU, not by actual CPU behavior.

**Review by gabrielesvelto — COMMENTED** [review]
This is mostly OK, I just left a comment to address.

File: minidump-processor/src/op_analysis.rs (hunk 1 above)
Comment (BrianShTsoi) [reply minidump-processor/src/op_analysis.rs:360]: Ah I was under the impression that `UCOMISS` has alignment requirements. Should have looked at the Intel manual more closely. And no I did not see any #GP crashes with `UCOMISS` without non-canonical address.
The QEMU bug causes an actual access violation instead of a GP, since it's accessing some extra bytes that it's not supposed to.

Comment (BrianShTsoi) [reply minidump-processor/src/op_analysis.rs:360]: @gabrielesvelto Is the QEMU bug the reason why you suggested in https://github.com/rust-minidump/rust-minidump/issues/732#issuecomment-2373323897 to drop non-canonical inconsistency detection for `UCOMISS`? If so it's probably fine to keep `UCOMISS` and only drop the detection for `MOVAPS`?

Comment (gabrielesvelto) [reply minidump-processor/src/op_analysis.rs:360]: Possibly, it was a mistake on my part.

Comment (BrianShTsoi) [reply minidump-processor/src/op_analysis.rs:360]: Ah ok, no worries. I'll change it to only dropping `MOVAPS`.

**Review by gabrielesvelto — APPROVED** [review]
Looking good
