### PR TITLE
Account for calls/jmps to non-canonical addresses.

### LINKED ISSUE #749: Fix up the crashing address in cases where we're jumping to a non-canonical address on x86-64
When we encounter a memory access that hits a non-canonical address we already replace the crashing address with the one we compute by disassembling the crashing instruction. This is because the general protection fault that gets delivered to the exception handler does not contain the address itself, so we have to recover it from the contents of the registers at the point of crash. Jumping to a non-canonical address also causes a GPF so we should also replace the crashing address if the access was to a non-canonical one.

### PR DESCRIPTION
**Pull request by afranchuk**
Closes #749, refactoring a few things along the way.

### CODE REVIEW

File: minidump-processor/src/op_analysis.rs [hunk 1]
```diff
@@ -153,62 +154,174 @@ mod amd64 {
...
+                        return Ok(());
+                    }
+                    // We assume that relative offsets (for CALL, JMP) and absolute values (CALLF,
+                    // JMPF) will be valid, so we don't check immediate operands, only registers.
+                    if let Operand::Register(reg) = decoded_instruction.operand(0) {
+                        let address = self.get_reg(reg)?;
+                        accesses.push(MemoryAccess {
+                            address,
+                            is_likely_null_pointer_dereference: address == 0,
+                            size: Some(1),
```
Comment (afranchuk) [inline minidump-processor/src/op_analysis.rs:300]: I wasn't sure whether this was appropriate or whether `None` would be better, since we don't know the actual read size.

File: minidump-processor/src/op_analysis.rs [hunk 2]
```diff
@@ -153,62 +154,174 @@ mod amd64 {
...
+                        });
+                    }
+                }
+                // TODO: if the full minidump information is plumbed down here, we can support
+                // RET/IRET as well (by reading the stack to get the return address)
```
Comment (afranchuk) [inline minidump-processor/src/op_analysis.rs:305]: It would be nice to use the stack information for this. The stack info could also be used to read any indirect calls (when they fall in stack memory), like `call [rax+8]`, which is probably common for vtables. If the minidump has heap memory that could be used too!

File: minidump-processor/src/op_analysis.rs (hunk 1 above)
Comment (gabrielesvelto) [reply minidump-processor/src/op_analysis.rs:300]: It's fine! Since x86 ISA variable-sized the first access by a jump instruction can be as small as one byte.

File: minidump-processor/src/op_analysis.rs (hunk 2 above)
Comment (gabrielesvelto) [reply minidump-processor/src/op_analysis.rs:305]: This is a worthy follow-up, I'll file an issue for it. I was considering doing it for `ret` but you're right that it might be more interesting to deal with vtables, especially those of dead objects which would automatically lead to a non-canonical access due to the poison pattern.

**Review by gabrielesvelto — APPROVED** [review]
LGTM, thanks!
